# Generated by Django 6.0.6 on 2026-06-16 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_type",
            field=models.IntegerField(
                choices=[(1, "audio file"), (1, "audio file"), (3, "pdf file")],
                default=1,
                verbose_name="file type",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="products.product",
                verbose_name="product",
            ),
        ),
    ]
