# Generated by Django 6.0.6 on 2026-06-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_file_file_type_alter_file_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to="files/%Y/%m/%d/", verbose_name="file"),
        ),
        migrations.AlterField(
            model_name="file",
            name="file_type",
            field=models.IntegerField(
                choices=[(1, "audio file"), (2, "video file"), (3, "pdf file")],
                default=1,
                verbose_name="file type",
            ),
        ),
    ]
